import type { VgcTeamPreset } from './vgcTeamPresets';

export const VGC_RECENT_CHAMPION_PRESETS: VgcTeamPreset[] = [
  {
    id: 'takuma-yamazaki-worlds-2026',
    title: '2026 World Champion',
    player: 'Takuma Yamazaki',
    event: '2026 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'Pokémon Champions Regulation M-B',
    mechanic: 'Double Mega Evolution',
    sourceUrl:
      'https://www.pokemon.com/us/play-pokemon/champions-gallery/takuma-yamazaki',
    pasteUrl: 'https://www.vrpastes.com/feLZkS21',
    year: 2026,
    members: [
      {
        pokemon: 'floette-eternal',
        set: {
          ability: 'Flower Veil',
          evs: { hp: 4, defense: 8, 'special-attack': 32, speed: 22 },
          item: 'Floettite',
          level: 50,
          mechanic: 'Mega Evolution · Fairy Aura',
          moves: ['Moonblast', 'Dazzling Gleam', 'Light of Ruin', 'Protect'],
          nature: 'Timid',
          trainingLabel: 'Training points',
        },
      },
      {
        pokemon: 'basculegion-male',
        set: {
          ability: 'Adaptability',
          evs: {
            hp: 4,
            attack: 18,
            defense: 4,
            'special-defense': 15,
            speed: 25,
          },
          gender: 'M',
          item: 'Life Orb',
          level: 50,
          moves: ['Wave Crash', 'Last Respects', 'Aqua Jet', 'Protect'],
          nature: 'Adamant',
          trainingLabel: 'Training points',
        },
      },
      {
        pokemon: 'kingambit',
        set: {
          ability: 'Defiant',
          evs: { hp: 32, attack: 15, 'special-defense': 19 },
          item: 'Chople Berry',
          level: 50,
          moves: ['Sucker Punch', 'Kowtow Cleave', 'Low Kick', 'Iron Head'],
          nature: 'Adamant',
          trainingLabel: 'Training points',
        },
      },
      {
        pokemon: 'dragonite',
        set: {
          ability: 'Multiscale',
          evs: { hp: 2, 'special-attack': 32, speed: 32 },
          item: 'Dragoninite',
          level: 50,
          mechanic: 'Mega Evolution · special attacking form',
          moves: ['Dragon Pulse', 'Heat Wave', 'Extreme Speed', 'Protect'],
          nature: 'Modest',
          trainingLabel: 'Training points',
        },
      },
      {
        pokemon: 'garchomp',
        set: {
          ability: 'Rough Skin',
          evs: { hp: 10, attack: 20, defense: 9, speed: 27 },
          item: 'Choice Scarf',
          level: 50,
          moves: [
            'Dragon Claw',
            'Stomping Tantrum',
            'Earthquake',
            'Rock Slide',
          ],
          nature: 'Adamant',
          trainingLabel: 'Training points',
        },
      },
      {
        pokemon: 'sneasler',
        set: {
          ability: 'Poison Touch',
          evs: { hp: 2, attack: 32, speed: 32 },
          item: 'Focus Sash',
          level: 50,
          moves: ['Close Combat', 'Dire Claw', 'Fake Out', 'Feint'],
          nature: 'Jolly',
          trainingLabel: 'Training points',
        },
      },
    ],
  },
  {
    id: 'giovanni-cischke-worlds-2025',
    title: '2025 World Champion',
    player: 'Giovanni Cischke',
    event: '2025 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'Scarlet and Violet Regulation I',
    mechanic: 'Terastallization',
    sourceUrl:
      'https://victoryroad.pro/2026/08/27/giovanni-cischke-worlds/',
    pasteUrl: 'https://www.vrpastes.com/VP48GdZh',
    year: 2025,
    members: [
      {
        pokemon: 'koraidon',
        set: {
          ability: 'Orichalcum Pulse',
          evs: { hp: 4, attack: 252, speed: 252 },
          item: 'Life Orb',
          level: 50,
          moves: ['Close Combat', 'Flare Blitz', 'Flame Charge', 'Protect'],
          nature: 'Jolly',
          teraType: 'Fire',
        },
      },
      {
        pokemon: 'lunala',
        set: {
          ability: 'Shadow Shield',
          evs: {
            hp: 204,
            defense: 28,
            'special-attack': 100,
            'special-defense': 116,
            speed: 60,
          },
          item: 'Power Herb',
          ivs: { attack: 0 },
          level: 50,
          moves: ['Moongeist Beam', 'Meteor Beam', 'Wide Guard', 'Trick Room'],
          nature: 'Modest',
          teraType: 'Water',
        },
      },
      {
        pokemon: 'flutter-mane',
        set: {
          ability: 'Protosynthesis',
          evs: { hp: 4, 'special-attack': 252, speed: 252 },
          item: 'Focus Sash',
          ivs: { attack: 3 },
          level: 50,
          moves: ['Shadow Ball', 'Moonblast', 'Icy Wind', 'Protect'],
          nature: 'Timid',
          teraType: 'Stellar',
        },
      },
      {
        pokemon: 'chi-yu',
        set: {
          ability: 'Beads of Ruin',
          evs: {
            hp: 52,
            defense: 4,
            'special-attack': 196,
            'special-defense': 4,
            speed: 252,
          },
          item: 'Choice Scarf',
          ivs: { attack: 1 },
          level: 50,
          moves: ['Dark Pulse', 'Heat Wave', 'Overheat', 'Snarl'],
          nature: 'Modest',
          teraType: 'Ghost',
        },
      },
      {
        pokemon: 'brute-bonnet',
        set: {
          ability: 'Protosynthesis',
          evs: { hp: 252, defense: 244, speed: 12 },
          item: 'Sitrus Berry',
          ivs: { 'special-attack': 28 },
          level: 50,
          moves: ['Seed Bomb', 'Sucker Punch', 'Spore', 'Rage Powder'],
          nature: 'Impish',
          teraType: 'Water',
        },
      },
      {
        pokemon: 'ursaluna',
        set: {
          ability: 'Guts',
          evs: { hp: 252, attack: 252, 'special-defense': 4 },
          gender: 'F',
          item: 'Flame Orb',
          ivs: { speed: 0 },
          level: 50,
          moves: ['Headlong Rush', 'Facade', 'Earthquake', 'Protect'],
          nature: 'Brave',
          teraType: 'Ghost',
        },
      },
    ],
  },
];
