import type { VgcTeamPreset } from './vgcTeamPresets';

export const VGC_SUPPLIED_CHAMPION_PRESETS: VgcTeamPreset[] = [
  {
    id: 'shohei-kimura-worlds-2023',
    title: '2023 World Champion',
    player: 'Shohei Kimura',
    event: '2023 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'Scarlet and Violet Regulation D',
    mechanic: 'Terastallization',
    sourceUrl: 'https://limitlessvgc.com/teams/950',
    year: 2023,
    members: [
      {
        pokemon: 'landorus-therian',
        set: {
          ability: 'Intimidate',
          evs: {},
          item: 'Safety Goggles',
          level: 50,
          moves: ['Stomping Tantrum', 'Tera Blast', 'U-turn', 'Protect'],
          nature: 'Not published',
          teraType: 'Flying',
        },
      },
      {
        pokemon: 'urshifu-rapid-strike',
        set: {
          ability: 'Unseen Fist',
          evs: {},
          item: 'Mystic Water',
          level: 50,
          moves: ['Surging Strikes', 'Aqua Jet', 'Protect', 'Taunt'],
          nature: 'Not published',
          teraType: 'Water',
        },
      },
      {
        pokemon: 'flutter-mane',
        set: {
          ability: 'Protosynthesis',
          evs: {},
          item: 'Choice Specs',
          level: 50,
          moves: ['Shadow Ball', 'Dazzling Gleam', 'Moonblast', 'Energy Ball'],
          nature: 'Not published',
          teraType: 'Grass',
        },
      },
      {
        pokemon: 'chien-pao',
        set: {
          ability: 'Sword of Ruin',
          evs: {},
          item: 'Focus Sash',
          level: 50,
          moves: ['Icicle Crash', 'Sacred Sword', 'Sucker Punch', 'Protect'],
          nature: 'Not published',
          teraType: 'Ghost',
        },
      },
      {
        pokemon: 'amoonguss',
        set: {
          ability: 'Regenerator',
          evs: {},
          item: 'Sitrus Berry',
          level: 50,
          moves: ['Pollen Puff', 'Spore', 'Rage Powder', 'Protect'],
          nature: 'Not published',
          teraType: 'Water',
        },
      },
      {
        pokemon: 'iron-hands',
        set: {
          ability: 'Quark Drive',
          evs: {},
          item: 'Assault Vest',
          level: 50,
          moves: ['Wild Charge', 'Volt Switch', 'Drain Punch', 'Fake Out'],
          nature: 'Not published',
          teraType: 'Water',
        },
      },
    ],
  },
  {
    id: 'ryota-otsubo-worlds-2017',
    title: '2017 World Champion',
    player: 'Ryota Otsubo',
    event: '2017 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2017',
    mechanic: 'Z-Moves',
    sourceUrl: 'https://limitlessvgc.com/teams/15',
    year: 2017,
    members: [
      {
        pokemon: 'tapu-fini',
        set: {
          ability: 'Misty Surge',
          evs: { hp: 204, 'special-attack': 212, speed: 92 },
          item: 'Choice Specs',
          level: 50,
          moves: ['Moonblast', 'Muddy Water', 'Dazzling Gleam', 'Ice Beam'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'krookodile',
        set: {
          ability: 'Intimidate',
          evs: {
            hp: 36,
            attack: 180,
            defense: 4,
            'special-defense': 84,
            speed: 204,
          },
          item: 'Groundium Z',
          level: 50,
          moves: ['Earthquake', 'Crunch', 'Taunt', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'whimsicott',
        set: {
          ability: 'Prankster',
          evs: { hp: 252, 'special-attack': 252, 'special-defense': 4 },
          item: 'Normalium Z',
          level: 50,
          moves: ['Nature Power', 'Tailwind', 'Charm', 'Protect'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'celesteela',
        set: {
          ability: 'Beast Boost',
          evs: {
            hp: 212,
            attack: 4,
            defense: 156,
            'special-defense': 76,
            speed: 60,
          },
          item: 'Leftovers',
          level: 50,
          moves: ['Heavy Slam', 'Flamethrower', 'Leech Seed', 'Protect'],
          nature: 'Careful',
        },
      },
      {
        pokemon: 'marowak-alola',
        set: {
          ability: 'Lightning Rod',
          evs: {
            hp: 252,
            attack: 20,
            defense: 4,
            'special-defense': 156,
            speed: 76,
          },
          item: 'Thick Club',
          level: 50,
          moves: ['Flare Blitz', 'Shadow Bone', 'Brick Break', 'Protect'],
          nature: 'Careful',
        },
      },
      {
        pokemon: 'tapu-koko',
        set: {
          ability: 'Electric Surge',
          evs: { 'special-attack': 252, 'special-defense': 4, speed: 252 },
          item: 'Life Orb',
          level: 50,
          moves: ['Thunderbolt', 'Dazzling Gleam', 'Discharge', 'Protect'],
          nature: 'Modest',
        },
      },
    ],
  },
  {
    id: 'wolfe-glick-worlds-2016',
    title: '2016 World Champion',
    player: 'Wolfe Glick',
    event: '2016 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2016',
    mechanic: 'Mega Evolution and Primal Reversion',
    sourceUrl: 'https://limitlessvgc.com/teams/1',
    year: 2016,
    members: [
      {
        pokemon: 'rayquaza-mega',
        set: {
          ability: 'Air Lock',
          evs: { hp: 4, attack: 252, speed: 252 },
          item: 'Focus Sash',
          level: 50,
          mechanic: 'Mega Evolution · Delta Stream',
          moves: ['Dragon Ascent', 'Protect', 'Swords Dance', 'Extreme Speed'],
          nature: 'Jolly',
        },
      },
      {
        pokemon: 'kyogre-primal',
        set: {
          ability: 'Drizzle',
          evs: {
            hp: 204,
            defense: 204,
            'special-attack': 44,
            'special-defense': 4,
            speed: 52,
          },
          item: 'Blue Orb',
          level: 50,
          mechanic: 'Primal Reversion · Primordial Sea',
          moves: ['Origin Pulse', 'Ice Beam', 'Water Spout', 'Protect'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'gengar-mega',
        set: {
          ability: 'Levitate',
          evs: {
            hp: 92,
            defense: 20,
            'special-attack': 172,
            'special-defense': 4,
            speed: 220,
          },
          item: 'Gengarite',
          level: 50,
          mechanic: 'Mega Evolution · Shadow Tag',
          moves: ['Protect', 'Taunt', 'Sludge Bomb', 'Will-O-Wisp'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'hitmontop',
        set: {
          ability: 'Intimidate',
          evs: {
            hp: 252,
            attack: 132,
            defense: 76,
            'special-defense': 44,
            speed: 4,
          },
          item: 'Eject Button',
          level: 50,
          moves: ['Wide Guard', 'Fake Out', 'Close Combat', 'Feint'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'raichu',
        set: {
          ability: 'Lightning Rod',
          evs: {
            hp: 36,
            defense: 204,
            'special-attack': 20,
            'special-defense': 68,
            speed: 180,
          },
          item: 'Assault Vest',
          level: 50,
          moves: ['Fake Out', 'Volt Switch', 'Endeavor', 'Nuzzle'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'bronzong',
        set: {
          ability: 'Levitate',
          evs: { hp: 252, defense: 68, 'special-defense': 188 },
          item: 'Lum Berry',
          level: 50,
          moves: ['Safeguard', 'Gyro Ball', 'Skill Swap', 'Trick Room'],
          nature: 'Sassy',
        },
      },
    ],
  },
  {
    id: 'sejun-park-worlds-2014',
    title: '2014 World Champion',
    player: 'Sejun Park',
    event: '2014 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2014',
    mechanic: 'Mega Evolution',
    sourceUrl: 'https://limitlessvgc.com/teams/39',
    year: 2014,
    members: [
      {
        pokemon: 'pachirisu',
        set: {
          ability: 'Volt Absorb',
          evs: { hp: 252, defense: 252, 'special-defense': 4 },
          item: 'Sitrus Berry',
          level: 50,
          moves: ['Nuzzle', 'Follow Me', 'Super Fang', 'Protect'],
          nature: 'Impish',
        },
      },
      {
        pokemon: 'gothitelle',
        set: {
          ability: 'Shadow Tag',
          evs: {
            hp: 252,
            defense: 172,
            'special-attack': 4,
            'special-defense': 76,
            speed: 4,
          },
          item: 'Leftovers',
          level: 50,
          moves: ['Psyshock', 'Thunder Wave', 'Tickle', 'Protect'],
          nature: 'Calm',
        },
      },
      {
        pokemon: 'gardevoir',
        set: {
          ability: 'Telepathy',
          evs: {
            hp: 4,
            defense: 44,
            'special-attack': 252,
            'special-defense': 4,
            speed: 204,
          },
          item: 'Choice Scarf',
          level: 50,
          moves: ['Dazzling Gleam', 'Psychic', 'Moonblast', 'Swagger'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'gyarados-mega',
        set: {
          ability: 'Intimidate',
          evs: { hp: 4, attack: 252, speed: 252 },
          item: 'Gyaradosite',
          level: 50,
          mechanic: 'Mega Evolution · Mold Breaker',
          moves: ['Dragon Dance', 'Waterfall', 'Earthquake', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'talonflame',
        set: {
          ability: 'Gale Wings',
          evs: { attack: 252, 'special-attack': 164, speed: 92 },
          item: 'Life Orb',
          level: 50,
          moves: ['Brave Bird', 'Overheat', 'Taunt', 'Quick Guard'],
          nature: 'Naive',
        },
      },
      {
        pokemon: 'garchomp',
        set: {
          ability: 'Rough Skin',
          evs: { hp: 4, attack: 252, speed: 252 },
          item: 'Focus Sash',
          level: 50,
          moves: ['Earthquake', 'Dragon Claw', 'Rock Slide', 'Protect'],
          nature: 'Jolly',
        },
      },
    ],
  },
];
