import type { VgcTeamPreset } from './vgcTeamPresets';

export const VGC_WORLD_CHAMPION_PRESETS: VgcTeamPreset[] = [
  {
    id: 'eduardo-cunha-worlds-2022',
    title: '2022 World Champion',
    player: 'Eduardo Cunha',
    event: '2022 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'Sword and Shield Series 12',
    mechanic: 'Dynamax and Gigantamax',
    sourceUrl:
      'https://www.nimbasacitypost.com/2022/12/vgc2022-series-12-sample-teams.html',
    pasteUrl: 'https://pokepast.es/040ead165b7a1072',
    year: 2022,
    members: [
      {
        pokemon: 'zacian-crowned',
        set: {
          ability: 'Intrepid Sword',
          evs: {
            hp: 252,
            attack: 76,
            defense: 28,
            'special-defense': 4,
            speed: 148,
          },
          item: 'Rusted Sword',
          level: 50,
          mechanic: 'Cannot Dynamax',
          moves: ['Behemoth Blade', 'Sacred Sword', 'Substitute', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'calyrex-shadow',
        set: {
          ability: 'As One (Spectrier)',
          evs: { hp: 4, 'special-attack': 252, speed: 252 },
          item: 'Focus Sash',
          ivs: { attack: 0 },
          level: 50,
          mechanic: 'Cannot Dynamax',
          moves: ['Astral Barrage', 'Snarl', 'Will-O-Wisp', 'Protect'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'incineroar',
        set: {
          ability: 'Intimidate',
          evs: {
            hp: 244,
            attack: 4,
            defense: 124,
            'special-defense': 108,
            speed: 28,
          },
          item: 'Safety Goggles',
          level: 50,
          moves: ['Flare Blitz', 'Throat Chop', 'Parting Shot', 'Fake Out'],
          nature: 'Impish',
        },
      },
      {
        pokemon: 'rillaboom-gmax',
        set: {
          ability: 'Grassy Surge',
          evs: {
            hp: 244,
            attack: 196,
            defense: 4,
            'special-defense': 60,
            speed: 4,
          },
          gender: 'M',
          item: 'Assault Vest',
          level: 50,
          mechanic: 'Gigantamax capable',
          moves: [
            'Fake Out',
            'Grassy Glide',
            'High Horsepower',
            'Knock Off',
          ],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'gastrodon',
        set: {
          ability: 'Storm Drain',
          evs: {
            hp: 180,
            defense: 92,
            'special-attack': 92,
            'special-defense': 144,
          },
          item: 'Leftovers',
          ivs: { attack: 0, speed: 8 },
          level: 50,
          mechanic: 'East Sea form',
          moves: ['Earth Power', 'Icy Wind', 'Yawn', 'Protect'],
          nature: 'Calm',
        },
      },
      {
        pokemon: 'thundurus-incarnate',
        set: {
          ability: 'Defiant',
          evs: { hp: 4, attack: 252, speed: 252 },
          item: 'Life Orb',
          level: 50,
          moves: ['Wild Charge', 'Fly', 'Taunt', 'Protect'],
          nature: 'Jolly',
        },
      },
    ],
  },
  {
    id: 'naoto-mizobuchi-worlds-2019',
    title: '2019 World Champion',
    player: 'Naoto Mizobuchi',
    event: '2019 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'Ultra Series',
    mechanic: 'Mega Evolution, Primal Reversion, and Z-Moves',
    sourceUrl:
      'https://victoryroad.pro/2019/08/29/world-champion-naoto-mizobuchi-report/',
    pasteUrl: 'https://limitlessvgc.com/teams/141/',
    year: 2019,
    members: [
      {
        pokemon: 'groudon',
        set: {
          ability: 'Drought',
          evs: { hp: 108, attack: 156, 'special-defense': 244 },
          item: 'Red Orb',
          level: 50,
          mechanic: 'Primal Reversion · Desolate Land',
          moves: ['Precipice Blades', 'Fire Punch', 'Dragon Claw', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'lunala',
        set: {
          ability: 'Shadow Shield',
          evs: { hp: 244, defense: 164, 'special-attack': 100 },
          item: 'Colbur Berry',
          ivs: { attack: 0, speed: 19 },
          level: 50,
          moves: ['Moongeist Beam', 'Wide Guard', 'Trick Room', 'Protect'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'salamence',
        set: {
          ability: 'Intimidate',
          evs: { hp: 36, 'special-defense': 244, speed: 228 },
          item: 'Salamencite',
          level: 50,
          mechanic: 'Mega Evolution · Aerilate',
          moves: ['Double-Edge', 'Hyper Voice', 'Tailwind', 'Protect'],
          nature: 'Hasty',
        },
      },
      {
        pokemon: 'tapu-fini',
        set: {
          ability: 'Misty Surge',
          evs: {
            hp: 244,
            defense: 4,
            'special-attack': 252,
            'special-defense': 4,
            speed: 4,
          },
          item: 'Fairium Z',
          ivs: { attack: 0 },
          level: 50,
          mechanic: 'Moonblast becomes Twinkle Tackle',
          moves: ["Moonblast", 'Scald', "Nature's Madness", 'Protect'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'incineroar',
        set: {
          ability: 'Intimidate',
          evs: {
            hp: 252,
            attack: 4,
            defense: 4,
            'special-defense': 236,
            speed: 12,
          },
          item: 'Assault Vest',
          level: 50,
          moves: ['Fake Out', 'Flare Blitz', 'Darkest Lariat', 'U-turn'],
          nature: 'Careful',
        },
      },
      {
        pokemon: 'stakataka',
        set: {
          ability: 'Beast Boost',
          evs: { hp: 252, attack: 252, 'special-defense': 4 },
          item: 'Rockium Z',
          ivs: { defense: 17, speed: 0 },
          level: 50,
          mechanic: 'Stone Edge becomes Continental Crush',
          moves: ['Gyro Ball', 'Stone Edge', 'Trick Room', 'Protect'],
          nature: 'Lonely',
        },
      },
    ],
  },
  {
    id: 'paul-ruiz-worlds-2018',
    title: '2018 World Champion',
    player: 'Paul Ruiz',
    event: '2018 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2018',
    mechanic: 'Mega Evolution and Z-Moves',
    sourceUrl:
      'https://victoryroad.pro/2018/09/14/soaring-higher-report-paul-ruiz-2018-world-champion/',
    pasteUrl: 'https://limitlessvgc.com/teams/23/',
    year: 2018,
    members: [
      {
        pokemon: 'salamence',
        set: {
          ability: 'Intimidate',
          evs: {
            hp: 44,
            attack: 228,
            defense: 4,
            'special-defense': 4,
            speed: 228,
          },
          item: 'Salamencite',
          level: 50,
          mechanic: 'Mega Evolution · Aerilate',
          moves: ['Double-Edge', 'Dragon Dance', 'Roost', 'Protect'],
          nature: 'Jolly',
        },
      },
      {
        pokemon: 'tapu-koko',
        set: {
          ability: 'Electric Surge',
          evs: {
            hp: 60,
            defense: 20,
            'special-attack': 164,
            'special-defense': 12,
            speed: 252,
          },
          item: 'Choice Specs',
          ivs: { attack: 0 },
          level: 50,
          moves: ['Thunderbolt', 'Dazzling Gleam', 'Volt Switch', 'Discharge'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'incineroar',
        set: {
          ability: 'Intimidate',
          evs: {
            hp: 236,
            attack: 4,
            defense: 12,
            'special-defense': 156,
            speed: 100,
          },
          item: 'Figy Berry',
          level: 50,
          moves: ['Flare Blitz', 'Snarl', 'Snatch', 'Fake Out'],
          nature: 'Careful',
        },
      },
      {
        pokemon: 'gastrodon',
        set: {
          ability: 'Storm Drain',
          evs: {
            hp: 180,
            defense: 212,
            'special-attack': 84,
            'special-defense': 28,
            speed: 4,
          },
          item: 'Groundium Z',
          ivs: { attack: 0 },
          level: 50,
          mechanic: 'Earth Power becomes Tectonic Rage',
          moves: ['Earth Power', 'Ice Beam', 'Recover', 'Protect'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'snorlax',
        set: {
          ability: 'Gluttony',
          evs: {
            hp: 68,
            attack: 4,
            defense: 220,
            'special-defense': 108,
            speed: 108,
          },
          item: 'Aguav Berry',
          level: 50,
          mechanic: '0 happiness for maximum Frustration power',
          moves: ['Frustration', 'Belly Drum', 'Recycle', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'kartana',
        set: {
          ability: 'Beast Boost',
          evs: {
            hp: 28,
            attack: 4,
            defense: 4,
            'special-defense': 244,
            speed: 228,
          },
          item: 'Grassium Z',
          level: 50,
          mechanic: 'Leaf Blade becomes Bloom Doom',
          moves: ['Leaf Blade', 'Sacred Sword', 'Tailwind', 'Protect'],
          nature: 'Adamant',
        },
      },
    ],
  },
  {
    id: 'shoma-honami-worlds-2015',
    title: '2015 World Champion',
    player: 'Shoma Honami',
    event: '2015 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2015',
    mechanic: 'Mega Evolution',
    sourceUrl:
      'https://nuggetbridge.com/reports/memoirs-world-champion-2015-world-champion-shadeviera/',
    pasteUrl: 'https://limitlessvgc.com/teams/31/',
    year: 2015,
    members: [
      {
        pokemon: 'kangaskhan',
        set: {
          ability: 'Scrappy',
          evs: {
            hp: 180,
            attack: 252,
            defense: 4,
            'special-defense': 12,
            speed: 60,
          },
          item: 'Kangaskhanite',
          level: 50,
          mechanic: 'Mega Evolution · Parental Bond',
          moves: ['Return', 'Low Kick', 'Sucker Punch', 'Fake Out'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'heatran',
        set: {
          ability: 'Flash Fire',
          evs: {
            hp: 244,
            defense: 4,
            'special-attack': 252,
            'special-defense': 4,
            speed: 4,
          },
          item: 'Shuca Berry',
          level: 50,
          moves: ['Heat Wave', 'Earth Power', 'Substitute', 'Protect'],
          nature: 'Modest',
        },
      },
      {
        pokemon: 'thundurus-incarnate',
        set: {
          ability: 'Prankster',
          evs: { hp: 252, 'special-defense': 252, speed: 4 },
          item: 'Safety Goggles',
          level: 50,
          moves: ['Thunderbolt', 'Thunder Wave', 'Swagger', 'Protect'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'landorus-therian',
        set: {
          ability: 'Intimidate',
          evs: { attack: 244, 'special-defense': 12, speed: 252 },
          item: 'Assault Vest',
          level: 50,
          moves: ['Earthquake', 'Superpower', 'Knock Off', 'Rock Slide'],
          nature: 'Jolly',
        },
      },
      {
        pokemon: 'cresselia',
        set: {
          ability: 'Levitate',
          evs: {
            hp: 244,
            defense: 4,
            'special-attack': 252,
            'special-defense': 4,
          },
          item: 'Sitrus Berry',
          ivs: { speed: 18 },
          level: 50,
          moves: ['Psychic', 'Ice Beam', 'Trick Room', 'Protect'],
          nature: 'Quiet',
        },
      },
      {
        pokemon: 'amoonguss',
        set: {
          ability: 'Regenerator',
          evs: { hp: 252, defense: 252, 'special-defense': 4 },
          item: 'Rocky Helmet',
          ivs: { speed: 0 },
          level: 50,
          moves: ['Energy Ball', 'Spore', 'Rage Powder', 'Sunny Day'],
          nature: 'Relaxed',
        },
      },
    ],
  },
  {
    id: 'arash-ommati-worlds-2013',
    title: '2013 World Champion',
    player: 'Arash Ommati',
    event: '2013 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2013',
    mechanic: 'Standard doubles',
    sourceUrl:
      'https://nuggetbridge.com/reports/mean-streets-world-champion-masters-2013-vgc-world-champion-report/',
    year: 2013,
    members: [
      {
        pokemon: 'mamoswine',
        set: {
          ability: 'Thick Fat',
          evs: {
            hp: 124,
            attack: 44,
            defense: 100,
            'special-defense': 44,
            speed: 196,
          },
          item: 'Choice Scarf',
          ivs: { 'special-attack': 1 },
          level: 50,
          moves: ['Icicle Spear', 'Earthquake', 'Icicle Crash', 'Rock Slide'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'tornadus-incarnate',
        set: {
          ability: 'Defiant',
          evs: { hp: 4, attack: 252, speed: 252 },
          item: 'Flying Gem',
          ivs: { 'special-attack': 3 },
          level: 50,
          moves: ['Acrobatics', 'Protect', 'Superpower', 'U-turn'],
          nature: 'Jolly',
        },
      },
      {
        pokemon: 'latios',
        set: {
          ability: 'Levitate',
          evs: { hp: 4, 'special-attack': 252, speed: 252 },
          item: 'Dragon Gem',
          ivs: { attack: 2, 'special-attack': 30, speed: 30 },
          level: 50,
          moves: ['Sunny Day', 'Draco Meteor', 'Protect', 'Hidden Power Fire'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'amoonguss',
        set: {
          ability: 'Regenerator',
          evs: { hp: 252, defense: 108, 'special-defense': 148 },
          item: 'Lum Berry',
          ivs: { attack: 0, speed: 7 },
          level: 50,
          moves: ['Spore', 'Rage Powder', 'Giga Drain', 'Protect'],
          nature: 'Calm',
        },
      },
      {
        pokemon: 'heatran',
        set: {
          ability: 'Flash Fire',
          evs: {
            hp: 212,
            defense: 4,
            'special-attack': 36,
            'special-defense': 4,
            speed: 252,
          },
          item: 'Leftovers',
          ivs: { attack: 0 },
          level: 50,
          moves: ['Substitute', 'Heat Wave', 'Protect', 'Earth Power'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'conkeldurr',
        set: {
          ability: 'Iron Fist',
          evs: {
            hp: 212,
            attack: 32,
            defense: 12,
            'special-defense': 252,
          },
          item: 'Sitrus Berry',
          ivs: { 'special-attack': 0 },
          level: 50,
          moves: ['Drain Punch', 'Ice Punch', 'Mach Punch', 'Protect'],
          nature: 'Adamant',
        },
      },
    ],
  },
  {
    id: 'ray-rizzo-worlds-2012',
    title: '2012 World Champion',
    player: 'Ray Rizzo',
    event: '2012 Pokémon World Championships',
    placing: '1st, Masters Division',
    format: 'VGC 2012',
    mechanic: 'Standard doubles',
    sourceUrl:
      'https://nuggetbridge.com/reports/third-times-the-charm-masters-world-champion-team-analysis/',
    pasteUrl: 'https://limitlessvgc.com/teams/224/',
    year: 2012,
    members: [
      {
        pokemon: 'cresselia',
        set: {
          ability: 'Levitate',
          evs: { hp: 220, defense: 108, 'special-attack': 180 },
          item: 'Sitrus Berry',
          ivs: { attack: 0, speed: 0 },
          level: 50,
          moves: ['Ice Beam', 'Psyshock', 'Swagger', 'Trick Room'],
          nature: 'Sassy',
        },
      },
      {
        pokemon: 'metagross',
        set: {
          ability: 'Clear Body',
          evs: {
            hp: 252,
            attack: 116,
            defense: 4,
            'special-defense': 136,
          },
          item: 'Lum Berry',
          ivs: { speed: 14 },
          level: 50,
          moves: ['Meteor Mash', 'Zen Headbutt', 'Earthquake', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'hydreigon',
        set: {
          ability: 'Levitate',
          evs: { hp: 60, 'special-attack': 252, speed: 196 },
          item: 'Dragon Gem',
          ivs: { attack: 0 },
          level: 50,
          moves: ['Draco Meteor', 'Dark Pulse', 'Flamethrower', 'Protect'],
          nature: 'Timid',
        },
      },
      {
        pokemon: 'garchomp',
        set: {
          ability: 'Sand Veil',
          evs: {
            hp: 36,
            attack: 116,
            defense: 4,
            'special-defense': 196,
            speed: 156,
          },
          item: 'Haban Berry',
          level: 50,
          moves: ['Dragon Claw', 'Earthquake', 'Substitute', 'Protect'],
          nature: 'Jolly',
        },
      },
      {
        pokemon: 'tyranitar',
        set: {
          ability: 'Sand Stream',
          evs: {
            hp: 252,
            attack: 124,
            defense: 36,
            'special-defense': 96,
          },
          item: 'Chople Berry',
          ivs: { speed: 0 },
          level: 50,
          moves: ['Rock Slide', 'Low Kick', 'Fire Punch', 'Protect'],
          nature: 'Adamant',
        },
      },
      {
        pokemon: 'rotom-wash',
        set: {
          ability: 'Levitate',
          evs: {
            hp: 228,
            defense: 4,
            'special-attack': 12,
            'special-defense': 12,
            speed: 252,
          },
          item: 'Choice Specs',
          ivs: { attack: 0 },
          level: 50,
          moves: ['Thunderbolt', 'Hydro Pump', 'Hidden Power Grass', 'Thunder'],
          nature: 'Modest',
        },
      },
    ],
  },
];
