const Quotes = [
    // Classic game quotes
    "I see now that one's birth is irrelevant. It's what you do that determines who you are. —Mewtwo",
    "Strong Pokémon. Weak Pokémon. That is only the selfish perception of people. —Karen",
    "There's no Pokemon that are useless in battle. —N",
    "My love for my friends permeates every cell of my body. —N",
    "Do you want to become strong? Prove it. —Cynthia",
    "When every life meets another life, something will be born. —Cynthia",
    "We do have a lot in common. The same earth, the same air, the same sky.",
    "I like shorts! They're comfy and easy to wear!",
    "Smell ya later! —Blue",
    "It's Ya Boy Guzma!",
    "It's been 3,000 years... —AZ",
    "The world isn't just black and white. —N",
    "That dream… Make it come true! Make your wonderful dream a reality! —N",
    "There's a time and place for everything. But not now. —Prof. Oak",
    "Are you a boy or a girl? —Prof. Oak",
    "I came when I heard you had beaten the Elite Four! —Prof. Oak",
    "Wake up! Today's the start of your adventure! —Mom",
    "Your Pokémon seem to be quite attached to you. —Cynthia",
    "Take this to Pokemon battles with you. —Prof. Oak",
    "You're not going to become strong by wishing for it. —Brawly",
    "The important thing is not how long you live. It's what you accomplish. —Ghetsis",
    "What we have in common is that we both want to help Pokémon. —Colress",
    "Wherever there is a meeting, a parting shall follow. —Aarune",
    "Having everything go your way is the road to disillusionment.",
    "Never give up! To do so is an insult to the Pokémon who fight for you!",
    "Change your perspective, and the reality changes.",
    "The lecturers at the Trainers' School always say that if you don't have any Pokémon to fight... use items!",
    "It's like my Rattata is in the top percentage of all Rattata! —Youngster Joey",
    "Ha ha! This gym is great! It's full of women! —Random NPC",
    "Today, we're dancing for no reason. Someday, we'll disappear for no reason.",
    "PEEKO MY DARLING! —Briney",
    "What is this pressure I feel? Something is enraged.",
    "I want to see things no one else can see. Know things no one else knows. —N",
    "...Erm, what was his name now? —Prof. Oak",
    "Make your Pokemon's direct hits land more by raising their accuracy!",
    "If you want to be strong, you have to evolve. —Lance",
    "The bond between a Trainer and Pokémon deepens over time. —Jasmine",
    "Trust your Pokémon. Your Pokémon will also trust you. —Iris",
    "Even if we don't understand each other, that's not a reason to reject each other. —N",
    "A Pokemon with Solar Power in Harsh Sunlight is devastatingly powerful.",
    "The spirits of Trainers who lost here are said to linger... —Lavender Town",
    "Be strong! Pokémon aren't meant for war! —Lt. Surge",
    "A Caterpie may change into a Butterfree, but the heart that beats inside remains the same.",
    "The circumstances of one's birth are irrelevant. —Mewtwo",
    "Knowledge is power, but knowing how to use it is what matters. —Steven",
    "Every storm eventually passes. —Wallace",
    "The answer lies in the heart of battle. —Koga",
    "Victory is won by those who believe in their bonds. —Alder",
    "A true rival pushes you to be better. —Silver",
    // Anime quotes
    "Gotta catch 'em all!",
    "Pika Pikaaa!",
    "Me give up? No way! —Ash",
    "There's no sense in going out of your way to get someone to like you. —Ash",
    "A Pokemon battle is about so much more than just winning or losing. —Ash",
    "You see, sometimes friends have to go away, but a part of them stays behind with you.",
    "That's okay, Brock. You'll find lots of other girls to reject you!",
    "Prepare for trouble! And make it double! —Team Rocket",
    "We're blasting off again! —Team Rocket",
    "Meowth, that's right! —Meowth",
    "The future is not a straight line. —Mewtwo",
    "Even if you lose in battle, if you surpass what you've done before, you've won. —Ash",
    "I failed. But I've gained precious things in that failure. —Ash",
    "If there's something you want to achieve, you can't give up. —Ash",
    "A real Pokemon Master keeps trying even when things look hopeless. —Ash",
    "Why are you leaving?! The sunset is so pretty! —Brock",
    "I'll use my trusty frying pan as a drying pan! —Brock",
    "There are bad ways to win and good ways to lose. —Ash",
    "Even the toughest trainers had to start somewhere.",
    "Make your Pokemon journey one worth remembering!",
    "We'll carry our memories with us, wherever we go. —Ash",
    "Friendship can show you things you've never seen before. —Misty",
    "You can't expect to win every single battle. —Brock",
    "Sometimes all you need is a little spark. —Pikachu",
    "A good Trainer never stops learning. —Professor Kukui",
    // Fun/meme quotes
    "DELELELELELEWOOOOOOOOP! —Kricketune",
    "Bidoof likes it.",
    "Walking Furret 🎵",
    "Giygogagohgwooh! —Dialga",
    "THUD!!!!!!",
    "ZZZZZZZZZZZZZZZZZZ —Snorlax",
    "Better than Bulbapedia!",
    "OnlyPokeFans",
    "Pokemon Masters Only",
    "Approved by Mew",
    "WHERE'S MY SUPERSUIT?! Wait... wrong franchise.",
    "Touch grass? I only touch tall grass. —Trainers",
    "Bottom screen? We don't do that here.",
    "Shiny hunting since before it was cool.",
    "Critical hit! It's super effective!",
    "The wild MISSINGNO. appeared!",
    "KAPOW!! ...Nothing happened. —Focus Blast",
    "A wild legendary appeared! ...Ran out of Pokéballs.",
    "99% accuracy means 0% accuracy. —Pokemon logic",
    "Did someone say Ice Beam? —Lapras",
    "You blacked out! You rushed to a Pokemon Center.",
    "Your rival's Pokémon fainted! Got ¥1200 for winning!",
    "Repel wore off. Anxiety rose.",
    "That one tile was definitely a hidden item.",
    "My starter is perfect and I will hear no criticism.",
    "No thoughts, head empty, only Pokéblocks.",
    "One more shiny hunt. I promise.",
    "Safari Zone logic is emotional damage.",
    "The bag is full. It is always full.",
    "Who needs sleep when the outbreak resets in 3 minutes?",
    "Exp. Share discourse never faints.",
    // Gen-specific
    "Wally wants to battle!",
    "Champion Cynthia would like to battle!",
    "Red wants to battle! ...Red: ...",
    "Volo would like to battle! ...Again.",
    "Nemona would like to battle! (for the 50th time)",
    "Toby Fox made a banger for Pokémon and nobody stopped him.",
    "Area Zero is calling...",
    "The Indigo Disk hits different.",
    "The Battle Frontier project has started!",
    "Meet me atop Mt. Silver. —Red",
    "The Distortion World still feels unreal.",
    "Ultra Wormholes were a choice.",
    "Hisuian forms stay winning.",
    "Paldea really said open world and meant it.",
    "Unova remakes when?",
    // Meta/dev
    "Developed by Rodrigo Ramirez",
    "Developed by Arceus",
    "Gotta search 'em all!",
    "Your Pokédex has been updated!",
    "Saving... Don't turn off the power.",
    "Connecting... Please stand by.",
    "Trade completed successfully.",
    "Mystery Gift received!",
    "PC box organized? Impossible.",
    "Rotom Phone battery: somehow still 100%.",
    "Pokédex progress is a lifestyle.",
    "Trainer tips are forever.",
    "This app is super effective.",
    "Now loading... wild encounters imminent.",
    "Press A to continue your adventure.",
];

export default Quotes;
